# Generated by Django 4.2.10 on 2024-03-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cooking_time', models.IntegerField()),
                ('image', models.ImageField(max_length=100)),
            ],
            options={
                'db_table': 'recipes_recipe',
                'managed': True,
            },
        ),
    ]
