# Generated by Django 4.2.10 on 2024-03-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='RecipesRecipe',
        ),
    ]
